version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: kelson
      POSTGRES_DB: banco
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
